# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireApi
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SDWebImageSwiftUI'
	

end
